-- ============================================================================
-- MIGRATION: Add snapshot metadata fields to projects table
-- Purpose: Store file count and total size from snapshots
-- Date: November 20, 2025
-- Phase: 2d - Snapshot Upload Integration
-- ============================================================================

-- Add snapshot metadata fields to projects table
ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS snapshot_file_count INTEGER;

ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS snapshot_total_size BIGINT;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_projects_snapshot_file_count 
  ON public.projects(snapshot_file_count DESC);

-- ============================================================================
-- EXPLANATION
-- ============================================================================

/*

NEW FIELDS:
- snapshot_file_count: Number of files included in the snapshot
  Type: INTEGER
  Used: Display file count to user, validation checks
  Updated: When snapshot is generated by Go agent

- snapshot_total_size: Total byte size of all files in snapshot
  Type: BIGINT (can handle files up to 8EB)
  Used: Display storage usage to user, storage quota calculations
  Updated: When snapshot is generated by Go agent

WORKFLOW:
1. Go agent generates snapshot locally (FileService)
2. Snapshot includes metadata: fileCount, totalSize
3. Go agent sends snapshot to POST /api/projects/:id/snapshot
4. Cloud backend:
   - Compresses snapshot JSON to gzip
   - Uploads to Supabase Storage (project-snapshots bucket)
   - Gets public URL
   - Updates projects table with:
     * snapshot_url (storage location)
     * snapshot_updated_at (ISO timestamp)
     * snapshot_file_count (from snapshot data)
     * snapshot_total_size (from snapshot data)

BENEFITS:
✓ File count/size available without decompressing snapshot
✓ Quick storage usage display in UI
✓ Support for quota management
✓ Database-level filtering for large projects
✓ Audit trail of snapshot metadata

BACKWARD COMPATIBILITY:
✓ Existing projects without snapshots will have NULL values
✓ Schema is additive - no breaking changes
✓ Old snapshots without metadata are still accessible via URL

USAGE IN CODE:
1. Receiving snapshot (Go agent):
   - FileService.GenerateSnapshot() returns: fileCount, totalSize
   - Sends to cloud: { snapshot: { ..., fileCount, totalSize }, syncStatus }

2. Storing metadata (Cloud backend):
   - POST /api/projects/:id/snapshot handler
   - Extracts fileCount and totalSize from request body
   - Updates projects table with both values
   - Logs for audit: fileCount, totalSize, syncStatus

3. Querying metadata (Electron):
   - GET /api/projects/:id returns project object
   - Display: snapshot_file_count + snapshot_total_size
   - Format: "1,234 files (45.2 MB)"

*/

-- ============================================================================
-- ROLLBACK
-- ============================================================================

/*
-- If you need to rollback this migration:

ALTER TABLE public.projects
DROP COLUMN IF EXISTS snapshot_file_count;

ALTER TABLE public.projects
DROP COLUMN IF EXISTS snapshot_total_size;

DROP INDEX IF EXISTS idx_projects_snapshot_file_count;

*/
